#!/usr/bin/env bash

if [ "$1" == "bin" ]; then
    shift 1
    
    docker run --rm \
        -u $(id -u):$(id -g) \
        -v $PWD:/app \
        -w /app \
        composer:latest ./vendor/bin/"$@"

else
    docker run --rm \
        -u $(id -u):$(id -g) \
        -v $PWD:/app \
        -w /app \
        composer:latest "$@"
fi